version: "2.1"
services:
  db:
    container_name: db
    image: postgres
  #   environment:
  #       POSTGRES_PASSWORD: postgres
  #       POSTGRES_USER: postgres
  #   ports:
  #     - 5432:5432
  adminer:
      image: adminer
      ports:
          - 8080:8080

  web:
      container_name: web
      build: .
      # image: node:8.4
      volumes:
        - $PWD:/app
      ports:
        - 3000:3000
      environment:
        - PGHOST=db
        - PGDATABASE=postgres
        - PGUSER=postgres

      # links:
      #   - db
