version: "2.1"
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
      image: adminer
      ports:
          - 8080:8080

  web:
      container_name: web
      build: .
      volumes:
        - $PWD:/app
      ports:
        - 3000:3000
      environment:
        - PGHOST=db
        - PGDATABASE=postgres
        - PGUSER=postgres
